###ai 43.202.32.94
post http://localhost:4000/ai
Content-Type: application/json; charset=UTF-8

{
    "device_number": "888777"
}

###ai 43.202.32.94
post http://localhost:4000/image
Content-Type: application/json; charset=UTF-8

{
    "device_number": "888777"
}
